import "./globals.css";
import LeftSidebar from "@/components/left-sidebar";
import RightSection from "@/components/right-section";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className="w-full h-full flex justify-center items-center relative bg-black">
      <div className="xl:max-w-[70vw] w-full h-full flex relative">
        <LeftSidebar />
        {children}
        <RightSection />
        </div>
       </div>
      </body>
    </html>
  );
}
